version: '3.2'

services: 
    db:
        hostname: 
            mysqldb
        image: mysql:5.7.31
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: pdk1234
            MYSQL_USER: pdk
            MYSQL_PASSWORD: pdk1234
            MYSQL_DATABASE: pdk
        ports: 
            - 3307:3306
        volumes:
            - ./mysql/data:/var/lib/mysql
    app:
        hostname: 
            app
        image: 
            kbzjung359/pdk-app:dev
        environment: 
            APP_SERVER: 0.0.0.0:8080
            REACT_SERVER: 0.0.0.0:3000
            DB_DRIVE: mysql
            DB_SERVER: db:3306
            DB_USER: pdk
            DB_PASS: pdk1234
            DB_DATABASE: pdk
        ports:
            - 80:8080
        depends_on: 
            - db
        links:
            - db