[server]
address = "10.27.24.2"
port = "8090"

[kafka]
broker = "220.70.2.1:9092"
group_id = "test"
topics = ["sensors"]
num_of_consumers = 500

[elastic]
addresses = ["http://220.70.2.1:9200/"]
request_retry = 3
chan_buf_size = 500
batch_ticker = 2
batch_size = 200

[appserver]
address = "http://220.70.2.5:80"

[mongodb]
address = "127.0.0.1"
port = "27017"
